[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@chainlink/=lib/chainlink-brownie-contracts/contracts/src/v0.8/',
    '@solmate/=lib/solmate/src/ERC20.sol',
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 256
